[mcp_servers.terraform]
command = "docker"
args = ["run", "-i", "--rm", "hashicorp/terraform-mcp-server:1.2.0"]
id = ""

[mcp_servers.terraform.env]

[mcp_servers."awslabs.aws-documentation-mcp-server"]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]
id = ""

[mcp_servers."awslabs.aws-documentation-mcp-server".env]
FASTMCP_LOG_LEVEL = "ERROR"
AWS_DOCUMENTATION_PARTITION = "aws"
MCP_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
